# Title of the page
title: Trayectoria
# Your name
author: Aaron GÃ¡lvez Salido
# Show a link to LinkedIn in the header intro. Comment out to disable.
# linkedin: 
# Show a link at the top of your timeline to your main personal site
# Comment this out to disable
personal_site:
  url: http://ags.aarongs.org/
  title: PÃ¡gina WEB personal
# show today marker at end of timeline
show_today: True

# Your timeline is split into periods (e.g., decades, childhood/teens/adult, "Before Timeliner"/"After Timeliner", etc)
# Each period has a list of events formatted as `- date: title`. If you don't want to have period dividers, leave out the name field.
periods:
  - events:
    - Septiembre 2017: "ğŸ”¬ Inicio de los estudios de Grado en BiologÃ­a."
    - Septiembre 2018: "ğŸº Inicio de actividad como Alumno interno en el departamento de ZoologÃ­a de la universidad de Granada."
    - Mayo 2018: "ğŸ“· RealizaciÃ³n de curso: IniciaciÃ³n a la FotografÃ­a CientÃ­fica , AsociaciÃ³n Darwin Eventur , 25 horas."
    - Mayo 2018: "ğŸ¤– RealizaciÃ³n de curso: Arduino : ConviÃ©rtete en un experto desde cero, AsociaciÃ³n Darwin Eventur , 120 horas."
    - Noviembre 2019: "ğŸ¾ RealizaciÃ³n de curso: Rastreo de Fauna Silvestre: MetodologÃ­a y Principios BÃ¡sicos Aplicables, AsociaciÃ³n Darwin Eventur , 40 horas."
    - Julio 2020: "ğŸ’» RealizaciÃ³n de curso: BioinformÃ¡tica de Muestras BiolÃ³gicas: BioestadÃ­stica Univariable y Multivariable Aplicada a Resultados con Muestras de SecuenciaciÃ³n Masiva, Centro MediterrÃ¡neo, 30 horas."
    - Abril 2021: "ğŸ’» RealizaciÃ³n de curso: Python Aplicado, Nivel Medio, AsociaciÃ³n Darwin Eventur, 80 horas."
    - Junio 2021: "ğŸº Fin de actividad como Alumno interno en el departamento de ZoologÃ­a de la universidad de Granada."
    - Julio 2021: "ğŸ§‘ğŸ¼â€ğŸ“ FinalizaciÃ³n de los estudios de Grado en BiologÃ­a."
    - Julio 2021: "ğŸ§¬ Inicio de actividad como colaborador del departamento de GenÃ©tica."
    - Octubre 2021: "ğŸ’» RealizaciÃ³n de curso: Especialista en BioinformÃ¡tica y BiologÃ­a computacional, Euroinnova, 200."
    - Noviembre 2021: "ğŸ¥³ AcreditaciÃ³n nivel C1 de Ingles (British Council)."
    - Abril 2022: "ğŸ’» RealizaciÃ³n de curso: MOOC Machine Learning y Big Data para la BioinformÃ¡tica, Abierta ugr, 100."
    - Julio 2022: "ğŸ¥³ PublicaciÃ³n de mi primer artÃ­culo: Una Calculadora de Genes para enseÃ±ar mendelismo, interacciones gÃ©nicas y ligamiento."
    - Agosto 2022: "ğŸ¤¿ AcreditaciÃ³n de buzo de aguas abiertas (PADI)."
  #- name: Granada
