# Title of the page
title: Trayectoria
# Your name
author: Aaron GÃ¡lvez Salido
# Show a link to LinkedIn in the header intro. Comment out to disable.
# linkedin: 
# Show a link at the top of your timeline to your main personal site
# Comment this out to disable
personal_site:
  url: http://ags.aarongs.org/
  title: PÃ¡gina WEB personal
# show today marker at end of timeline
show_today: false

# Your timeline is split into periods (e.g., decades, childhood/teens/adult, "Before Timeliner"/"After Timeliner", etc)
# Each period has a list of events formatted as `- date: title`. If you don't want to have period dividers, leave out the name field.
periods:
  - events:
    - Septiembre 2017: "ğŸ”¬ Inicio de los estudios de Grado en BiologÃ­a"
    - Julio 2021: "ğŸ§‘ğŸ¼â€ğŸ“ FinalizaciÃ³n de los estudios de Grado en BiologÃ­a"
  #- name: Granada
